# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot
version: 2

multi-ecosystem-groups:
  bau-deps:
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "bau-deps"
  - package-ecosystem: gomod
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "bau-deps"
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "bau-deps"