name: Workforce CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read # Optional: allow read access to pull request. Use with `only-new-issues` option.

jobs:
  workforce-ci:
    name: CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
      - name: Setup Go Environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.25' # Specify your desired Go version
          cache: true
          cache-dependency-path: "**/*.sum"
      - name: Build
        run: go build ./...
      - name: Run Go tests
        run: go test -v ./...    
      - name: Lint it
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1 # Specify the golangci-lint version
          args: --timeout=5m # Example argument: set a timeout for linting